# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bill for Selectman
email: billwagnerforselectman@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bill Wagner for Rockport's Board of Selectman in 2020.
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Bill Wagner"
  avatar : "/assets/images/headshot.jpg"
  bio    : "[`billwagnerforselectman@gmail.com`](mailto:billwagnerforselectman@gmail.com)"

  links:
    - label: "Pigeon Cove, MA"
      icon: "fa fa-fw fa-map-marker"
      url: "https://goo.gl/maps/G97De9kQgxBhCdNAA"
  
footer:
  links:
    - label: "billwagnerforselectman@gmail.com"
      icon: "fa fa-fw fa-envelope-square"
      url: "mailto:billwagnerforselectman@gmail.com"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
